version: '3.8'
services:
  web:
    build:
      context: ./
      target: runner
    volumes:
      - ./components:/app/components
      - ./interfaces:/app/interfaces
      - ./pages:/app/pages
      - ./data:/app/data
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
